# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wyf/PIM4DB-May2021-SP1/MonetDB-11.39.11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wyf/PIM4DB-May2021-SP1/MonetDB-11.39.11/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"client\" \"clientdev\" \"clienttest\" \"mclient\" \"microbenchmark\" \"monetdb\" \"monetdbdev\" \"odbc\" \"pytesting\" \"run_adder\" \"run_isolate\" \"run_memo\" \"server\" \"serverdev\" \"sql\" \"stream\" \"streamdev\" \"testing\" \"tools\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/wyf/PIM4DB-May2021-SP1/MonetDB-11.39.11/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wyf/PIM4DB-May2021-SP1/MonetDB-11.39.11/build/CMakeFiles /home/wyf/PIM4DB-May2021-SP1/MonetDB-11.39.11/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wyf/PIM4DB-May2021-SP1/MonetDB-11.39.11/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named create-source-deb-packages

# Build rule for target.
create-source-deb-packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-source-deb-packages
.PHONY : create-source-deb-packages

# fast build rule for target.
create-source-deb-packages/fast:
	$(MAKE) -f CMakeFiles/create-source-deb-packages.dir/build.make CMakeFiles/create-source-deb-packages.dir/build
.PHONY : create-source-deb-packages/fast

#=============================================================================
# Target rules for targets named create-deb-packages

# Build rule for target.
create-deb-packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-deb-packages
.PHONY : create-deb-packages

# fast build rule for target.
create-deb-packages/fast:
	$(MAKE) -f CMakeFiles/create-deb-packages.dir/build.make CMakeFiles/create-deb-packages.dir/build
.PHONY : create-deb-packages/fast

#=============================================================================
# Target rules for targets named create-rpm-packages

# Build rule for target.
create-rpm-packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-rpm-packages
.PHONY : create-rpm-packages

# fast build rule for target.
create-rpm-packages/fast:
	$(MAKE) -f CMakeFiles/create-rpm-packages.dir/build.make CMakeFiles/create-rpm-packages.dir/build
.PHONY : create-rpm-packages/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named create-source-rpm-packages

# Build rule for target.
create-source-rpm-packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-source-rpm-packages
.PHONY : create-source-rpm-packages

# fast build rule for target.
create-source-rpm-packages/fast:
	$(MAKE) -f CMakeFiles/create-source-rpm-packages.dir/build.make CMakeFiles/create-source-rpm-packages.dir/build
.PHONY : create-source-rpm-packages/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named create-rpm-distro

# Build rule for target.
create-rpm-distro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-rpm-distro
.PHONY : create-rpm-distro

# fast build rule for target.
create-rpm-distro/fast:
	$(MAKE) -f CMakeFiles/create-rpm-distro.dir/build.make CMakeFiles/create-rpm-distro.dir/build
.PHONY : create-rpm-distro/fast

#=============================================================================
# Target rules for targets named mtest

# Build rule for target.
mtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mtest
.PHONY : mtest

# fast build rule for target.
mtest/fast:
	$(MAKE) -f CMakeFiles/mtest.dir/build.make CMakeFiles/mtest.dir/build
.PHONY : mtest/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named create-rpm-repo

# Build rule for target.
create-rpm-repo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-rpm-repo
.PHONY : create-rpm-repo

# fast build rule for target.
create-rpm-repo/fast:
	$(MAKE) -f CMakeFiles/create-rpm-repo.dir/build.make CMakeFiles/create-rpm-repo.dir/build
.PHONY : create-rpm-repo/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named create-wix-packages

# Build rule for target.
create-wix-packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create-wix-packages
.PHONY : create-wix-packages

# fast build rule for target.
create-wix-packages/fast:
	$(MAKE) -f CMakeFiles/create-wix-packages.dir/build.make CMakeFiles/create-wix-packages.dir/build
.PHONY : create-wix-packages/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named moptions

# Build rule for target.
moptions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moptions
.PHONY : moptions

# fast build rule for target.
moptions/fast:
	$(MAKE) -f common/options/CMakeFiles/moptions.dir/build.make common/options/CMakeFiles/moptions.dir/build
.PHONY : moptions/fast

#=============================================================================
# Target rules for targets named stream

# Build rule for target.
stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream
.PHONY : stream

# fast build rule for target.
stream/fast:
	$(MAKE) -f common/stream/CMakeFiles/stream.dir/build.make common/stream/CMakeFiles/stream.dir/build
.PHONY : stream/fast

#=============================================================================
# Target rules for targets named mutils

# Build rule for target.
mutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mutils
.PHONY : mutils

# fast build rule for target.
mutils/fast:
	$(MAKE) -f common/utils/CMakeFiles/mutils.dir/build.make common/utils/CMakeFiles/mutils.dir/build
.PHONY : mutils/fast

#=============================================================================
# Target rules for targets named mcrypt

# Build rule for target.
mcrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcrypt
.PHONY : mcrypt

# fast build rule for target.
mcrypt/fast:
	$(MAKE) -f common/utils/CMakeFiles/mcrypt.dir/build.make common/utils/CMakeFiles/mcrypt.dir/build
.PHONY : mcrypt/fast

#=============================================================================
# Target rules for targets named msabaoth

# Build rule for target.
msabaoth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msabaoth
.PHONY : msabaoth

# fast build rule for target.
msabaoth/fast:
	$(MAKE) -f common/utils/CMakeFiles/msabaoth.dir/build.make common/utils/CMakeFiles/msabaoth.dir/build
.PHONY : msabaoth/fast

#=============================================================================
# Target rules for targets named mprompt

# Build rule for target.
mprompt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mprompt
.PHONY : mprompt

# fast build rule for target.
mprompt/fast:
	$(MAKE) -f common/utils/CMakeFiles/mprompt.dir/build.make common/utils/CMakeFiles/mprompt.dir/build
.PHONY : mprompt/fast

#=============================================================================
# Target rules for targets named msqldump

# Build rule for target.
msqldump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msqldump
.PHONY : msqldump

# fast build rule for target.
msqldump/fast:
	$(MAKE) -f clients/mapiclient/CMakeFiles/msqldump.dir/build.make clients/mapiclient/CMakeFiles/msqldump.dir/build
.PHONY : msqldump/fast

#=============================================================================
# Target rules for targets named mclient

# Build rule for target.
mclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mclient
.PHONY : mclient

# fast build rule for target.
mclient/fast:
	$(MAKE) -f clients/mapiclient/CMakeFiles/mclient.dir/build.make clients/mapiclient/CMakeFiles/mclient.dir/build
.PHONY : mclient/fast

#=============================================================================
# Target rules for targets named stethoscope

# Build rule for target.
stethoscope: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stethoscope
.PHONY : stethoscope

# fast build rule for target.
stethoscope/fast:
	$(MAKE) -f clients/mapiclient/CMakeFiles/stethoscope.dir/build.make clients/mapiclient/CMakeFiles/stethoscope.dir/build
.PHONY : stethoscope/fast

#=============================================================================
# Target rules for targets named mcutil

# Build rule for target.
mcutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcutil
.PHONY : mcutil

# fast build rule for target.
mcutil/fast:
	$(MAKE) -f clients/mapiclient/CMakeFiles/mcutil.dir/build.make clients/mapiclient/CMakeFiles/mcutil.dir/build
.PHONY : mcutil/fast

#=============================================================================
# Target rules for targets named mapi

# Build rule for target.
mapi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapi
.PHONY : mapi

# fast build rule for target.
mapi/fast:
	$(MAKE) -f clients/mapilib/CMakeFiles/mapi.dir/build.make clients/mapilib/CMakeFiles/mapi.dir/build
.PHONY : mapi/fast

#=============================================================================
# Target rules for targets named MonetODBCs

# Build rule for target.
MonetODBCs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MonetODBCs
.PHONY : MonetODBCs

# fast build rule for target.
MonetODBCs/fast:
	$(MAKE) -f clients/odbc/setup/CMakeFiles/MonetODBCs.dir/build.make clients/odbc/setup/CMakeFiles/MonetODBCs.dir/build
.PHONY : MonetODBCs/fast

#=============================================================================
# Target rules for targets named MonetODBC

# Build rule for target.
MonetODBC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MonetODBC
.PHONY : MonetODBC

# fast build rule for target.
MonetODBC/fast:
	$(MAKE) -f clients/odbc/driver/CMakeFiles/MonetODBC.dir/build.make clients/odbc/driver/CMakeFiles/MonetODBC.dir/build
.PHONY : MonetODBC/fast

#=============================================================================
# Target rules for targets named testStmtAttr

# Build rule for target.
testStmtAttr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testStmtAttr
.PHONY : testStmtAttr

# fast build rule for target.
testStmtAttr/fast:
	$(MAKE) -f clients/odbc/samples/CMakeFiles/testStmtAttr.dir/build.make clients/odbc/samples/CMakeFiles/testStmtAttr.dir/build
.PHONY : testStmtAttr/fast

#=============================================================================
# Target rules for targets named arraytest

# Build rule for target.
arraytest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arraytest
.PHONY : arraytest

# fast build rule for target.
arraytest/fast:
	$(MAKE) -f clients/odbc/samples/CMakeFiles/arraytest.dir/build.make clients/odbc/samples/CMakeFiles/arraytest.dir/build
.PHONY : arraytest/fast

#=============================================================================
# Target rules for targets named testgetinfo

# Build rule for target.
testgetinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testgetinfo
.PHONY : testgetinfo

# fast build rule for target.
testgetinfo/fast:
	$(MAKE) -f clients/odbc/samples/CMakeFiles/testgetinfo.dir/build.make clients/odbc/samples/CMakeFiles/testgetinfo.dir/build
.PHONY : testgetinfo/fast

#=============================================================================
# Target rules for targets named odbcsample1

# Build rule for target.
odbcsample1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odbcsample1
.PHONY : odbcsample1

# fast build rule for target.
odbcsample1/fast:
	$(MAKE) -f clients/odbc/samples/CMakeFiles/odbcsample1.dir/build.make clients/odbc/samples/CMakeFiles/odbcsample1.dir/build
.PHONY : odbcsample1/fast

#=============================================================================
# Target rules for targets named sample1

# Build rule for target.
sample1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample1
.PHONY : sample1

# fast build rule for target.
sample1/fast:
	$(MAKE) -f clients/examples/C/CMakeFiles/sample1.dir/build.make clients/examples/C/CMakeFiles/sample1.dir/build
.PHONY : sample1/fast

#=============================================================================
# Target rules for targets named smack00

# Build rule for target.
smack00: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smack00
.PHONY : smack00

# fast build rule for target.
smack00/fast:
	$(MAKE) -f clients/examples/C/CMakeFiles/smack00.dir/build.make clients/examples/C/CMakeFiles/smack00.dir/build
.PHONY : smack00/fast

#=============================================================================
# Target rules for targets named smack01

# Build rule for target.
smack01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smack01
.PHONY : smack01

# fast build rule for target.
smack01/fast:
	$(MAKE) -f clients/examples/C/CMakeFiles/smack01.dir/build.make clients/examples/C/CMakeFiles/smack01.dir/build
.PHONY : smack01/fast

#=============================================================================
# Target rules for targets named streamcat

# Build rule for target.
streamcat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 streamcat
.PHONY : streamcat

# fast build rule for target.
streamcat/fast:
	$(MAKE) -f clients/examples/C/CMakeFiles/streamcat.dir/build.make clients/examples/C/CMakeFiles/streamcat.dir/build
.PHONY : streamcat/fast

#=============================================================================
# Target rules for targets named sample4

# Build rule for target.
sample4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample4
.PHONY : sample4

# fast build rule for target.
sample4/fast:
	$(MAKE) -f clients/examples/C/CMakeFiles/sample4.dir/build.make clients/examples/C/CMakeFiles/sample4.dir/build
.PHONY : sample4/fast

#=============================================================================
# Target rules for targets named sample0

# Build rule for target.
sample0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample0
.PHONY : sample0

# fast build rule for target.
sample0/fast:
	$(MAKE) -f clients/examples/C/CMakeFiles/sample0.dir/build.make clients/examples/C/CMakeFiles/sample0.dir/build
.PHONY : sample0/fast

#=============================================================================
# Target rules for targets named bat

# Build rule for target.
bat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bat
.PHONY : bat

# fast build rule for target.
bat/fast:
	$(MAKE) -f gdk/CMakeFiles/bat.dir/build.make gdk/CMakeFiles/bat.dir/build
.PHONY : bat/fast

#=============================================================================
# Target rules for targets named mal

# Build rule for target.
mal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mal
.PHONY : mal

# fast build rule for target.
mal/fast:
	$(MAKE) -f monetdb5/mal/CMakeFiles/mal.dir/build.make monetdb5/mal/CMakeFiles/mal.dir/build
.PHONY : mal/fast

#=============================================================================
# Target rules for targets named atoms

# Build rule for target.
atoms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atoms
.PHONY : atoms

# fast build rule for target.
atoms/fast:
	$(MAKE) -f monetdb5/modules/atoms/CMakeFiles/atoms.dir/build.make monetdb5/modules/atoms/CMakeFiles/atoms.dir/build
.PHONY : atoms/fast

#=============================================================================
# Target rules for targets named malmodules

# Build rule for target.
malmodules: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 malmodules
.PHONY : malmodules

# fast build rule for target.
malmodules/fast:
	$(MAKE) -f monetdb5/modules/mal/CMakeFiles/malmodules.dir/build.make monetdb5/modules/mal/CMakeFiles/malmodules.dir/build
.PHONY : malmodules/fast

#=============================================================================
# Target rules for targets named microbenchmark

# Build rule for target.
microbenchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 microbenchmark
.PHONY : microbenchmark

# fast build rule for target.
microbenchmark/fast:
	$(MAKE) -f monetdb5/modules/kernel/CMakeFiles/microbenchmark.dir/build.make monetdb5/modules/kernel/CMakeFiles/microbenchmark.dir/build
.PHONY : microbenchmark/fast

#=============================================================================
# Target rules for targets named kernel

# Build rule for target.
kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel
.PHONY : kernel

# fast build rule for target.
kernel/fast:
	$(MAKE) -f monetdb5/modules/kernel/CMakeFiles/kernel.dir/build.make monetdb5/modules/kernel/CMakeFiles/kernel.dir/build
.PHONY : kernel/fast

#=============================================================================
# Target rules for targets named optimizer

# Build rule for target.
optimizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optimizer
.PHONY : optimizer

# fast build rule for target.
optimizer/fast:
	$(MAKE) -f monetdb5/optimizer/CMakeFiles/optimizer.dir/build.make monetdb5/optimizer/CMakeFiles/optimizer.dir/build
.PHONY : optimizer/fast

#=============================================================================
# Target rules for targets named run_isolate

# Build rule for target.
run_isolate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_isolate
.PHONY : run_isolate

# fast build rule for target.
run_isolate/fast:
	$(MAKE) -f monetdb5/scheduler/CMakeFiles/run_isolate.dir/build.make monetdb5/scheduler/CMakeFiles/run_isolate.dir/build
.PHONY : run_isolate/fast

#=============================================================================
# Target rules for targets named run_memo

# Build rule for target.
run_memo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_memo
.PHONY : run_memo

# fast build rule for target.
run_memo/fast:
	$(MAKE) -f monetdb5/scheduler/CMakeFiles/run_memo.dir/build.make monetdb5/scheduler/CMakeFiles/run_memo.dir/build
.PHONY : run_memo/fast

#=============================================================================
# Target rules for targets named run_adder

# Build rule for target.
run_adder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_adder
.PHONY : run_adder

# fast build rule for target.
run_adder/fast:
	$(MAKE) -f monetdb5/scheduler/CMakeFiles/run_adder.dir/build.make monetdb5/scheduler/CMakeFiles/run_adder.dir/build
.PHONY : run_adder/fast

#=============================================================================
# Target rules for targets named monetdb5

# Build rule for target.
monetdb5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monetdb5
.PHONY : monetdb5

# fast build rule for target.
monetdb5/fast:
	$(MAKE) -f monetdb5/tools/CMakeFiles/monetdb5.dir/build.make monetdb5/tools/CMakeFiles/monetdb5.dir/build
.PHONY : monetdb5/fast

#=============================================================================
# Target rules for targets named opt_sql_append

# Build rule for target.
opt_sql_append: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opt_sql_append
.PHONY : opt_sql_append

# fast build rule for target.
opt_sql_append/fast:
	$(MAKE) -f monetdb5/extras/mal_optimizer_template/CMakeFiles/opt_sql_append.dir/build.make monetdb5/extras/mal_optimizer_template/CMakeFiles/opt_sql_append.dir/build
.PHONY : opt_sql_append/fast

#=============================================================================
# Target rules for targets named sql

# Build rule for target.
sql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sql
.PHONY : sql

# fast build rule for target.
sql/fast:
	$(MAKE) -f sql/backends/monet5/CMakeFiles/sql.dir/build.make sql/backends/monet5/CMakeFiles/sql.dir/build
.PHONY : sql/fast

#=============================================================================
# Target rules for targets named generator

# Build rule for target.
generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generator
.PHONY : generator

# fast build rule for target.
generator/fast:
	$(MAKE) -f sql/backends/monet5/generator/CMakeFiles/generator.dir/build.make sql/backends/monet5/generator/CMakeFiles/generator.dir/build
.PHONY : generator/fast

#=============================================================================
# Target rules for targets named udf

# Build rule for target.
udf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udf
.PHONY : udf

# fast build rule for target.
udf/fast:
	$(MAKE) -f sql/backends/monet5/UDF/udf/CMakeFiles/udf.dir/build.make sql/backends/monet5/UDF/udf/CMakeFiles/udf.dir/build
.PHONY : udf/fast

#=============================================================================
# Target rules for targets named capi

# Build rule for target.
capi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capi
.PHONY : capi

# fast build rule for target.
capi/fast:
	$(MAKE) -f sql/backends/monet5/UDF/capi/CMakeFiles/capi.dir/build.make sql/backends/monet5/UDF/capi/CMakeFiles/capi.dir/build
.PHONY : capi/fast

#=============================================================================
# Target rules for targets named pyapi3

# Build rule for target.
pyapi3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pyapi3
.PHONY : pyapi3

# fast build rule for target.
pyapi3/fast:
	$(MAKE) -f sql/backends/monet5/UDF/pyapi3/CMakeFiles/pyapi3.dir/build.make sql/backends/monet5/UDF/pyapi3/CMakeFiles/pyapi3.dir/build
.PHONY : pyapi3/fast

#=============================================================================
# Target rules for targets named sqlcommon

# Build rule for target.
sqlcommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlcommon
.PHONY : sqlcommon

# fast build rule for target.
sqlcommon/fast:
	$(MAKE) -f sql/common/CMakeFiles/sqlcommon.dir/build.make sql/common/CMakeFiles/sqlcommon.dir/build
.PHONY : sqlcommon/fast

#=============================================================================
# Target rules for targets named sqlserver

# Build rule for target.
sqlserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlserver
.PHONY : sqlserver

# fast build rule for target.
sqlserver/fast:
	$(MAKE) -f sql/server/CMakeFiles/sqlserver.dir/build.make sql/server/CMakeFiles/sqlserver.dir/build
.PHONY : sqlserver/fast

#=============================================================================
# Target rules for targets named sqlstorage

# Build rule for target.
sqlstorage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlstorage
.PHONY : sqlstorage

# fast build rule for target.
sqlstorage/fast:
	$(MAKE) -f sql/storage/CMakeFiles/sqlstorage.dir/build.make sql/storage/CMakeFiles/sqlstorage.dir/build
.PHONY : sqlstorage/fast

#=============================================================================
# Target rules for targets named batstore

# Build rule for target.
batstore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 batstore
.PHONY : batstore

# fast build rule for target.
batstore/fast:
	$(MAKE) -f sql/storage/bat/CMakeFiles/batstore.dir/build.make sql/storage/bat/CMakeFiles/batstore.dir/build
.PHONY : batstore/fast

#=============================================================================
# Target rules for targets named monetdb

# Build rule for target.
monetdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monetdb
.PHONY : monetdb

# fast build rule for target.
monetdb/fast:
	$(MAKE) -f tools/merovingian/client/CMakeFiles/monetdb.dir/build.make tools/merovingian/client/CMakeFiles/monetdb.dir/build
.PHONY : monetdb/fast

#=============================================================================
# Target rules for targets named monetdbd

# Build rule for target.
monetdbd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monetdbd
.PHONY : monetdbd

# fast build rule for target.
monetdbd/fast:
	$(MAKE) -f tools/merovingian/daemon/CMakeFiles/monetdbd.dir/build.make tools/merovingian/daemon/CMakeFiles/monetdbd.dir/build
.PHONY : monetdbd/fast

#=============================================================================
# Target rules for targets named meroutil

# Build rule for target.
meroutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 meroutil
.PHONY : meroutil

# fast build rule for target.
meroutil/fast:
	$(MAKE) -f tools/merovingian/utils/CMakeFiles/meroutil.dir/build.make tools/merovingian/utils/CMakeFiles/meroutil.dir/build
.PHONY : meroutil/fast

#=============================================================================
# Target rules for targets named shutdowntest

# Build rule for target.
shutdowntest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shutdowntest
.PHONY : shutdowntest

# fast build rule for target.
shutdowntest/fast:
	$(MAKE) -f tools/mserver/CMakeFiles/shutdowntest.dir/build.make tools/mserver/CMakeFiles/shutdowntest.dir/build
.PHONY : shutdowntest/fast

#=============================================================================
# Target rules for targets named mserver5

# Build rule for target.
mserver5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mserver5
.PHONY : mserver5

# fast build rule for target.
mserver5/fast:
	$(MAKE) -f tools/mserver/CMakeFiles/mserver5.dir/build.make tools/mserver/CMakeFiles/mserver5.dir/build
.PHONY : mserver5/fast

#=============================================================================
# Target rules for targets named monetdbe

# Build rule for target.
monetdbe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monetdbe
.PHONY : monetdbe

# fast build rule for target.
monetdbe/fast:
	$(MAKE) -f tools/monetdbe/CMakeFiles/monetdbe.dir/build.make tools/monetdbe/CMakeFiles/monetdbe.dir/build
.PHONY : monetdbe/fast

#=============================================================================
# Target rules for targets named Mdiff

# Build rule for target.
Mdiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mdiff
.PHONY : Mdiff

# fast build rule for target.
Mdiff/fast:
	$(MAKE) -f testing/CMakeFiles/Mdiff.dir/build.make testing/CMakeFiles/Mdiff.dir/build
.PHONY : Mdiff/fast

#=============================================================================
# Target rules for targets named test_malInclude

# Build rule for target.
test_malInclude: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_malInclude
.PHONY : test_malInclude

# fast build rule for target.
test_malInclude/fast:
	$(MAKE) -f ctest/monetdb5/mal/CMakeFiles/test_malInclude.dir/build.make ctest/monetdb5/mal/CMakeFiles/test_malInclude.dir/build
.PHONY : test_malInclude/fast

#=============================================================================
# Target rules for targets named test_malEmbeddedBoot

# Build rule for target.
test_malEmbeddedBoot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_malEmbeddedBoot
.PHONY : test_malEmbeddedBoot

# fast build rule for target.
test_malEmbeddedBoot/fast:
	$(MAKE) -f ctest/monetdb5/mal/CMakeFiles/test_malEmbeddedBoot.dir/build.make ctest/monetdb5/mal/CMakeFiles/test_malEmbeddedBoot.dir/build
.PHONY : test_malEmbeddedBoot/fast

#=============================================================================
# Target rules for targets named example1

# Build rule for target.
example1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example1
.PHONY : example1

# fast build rule for target.
example1/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example1.dir/build.make ctest/tools/monetdbe/CMakeFiles/example1.dir/build
.PHONY : example1/fast

#=============================================================================
# Target rules for targets named example_remote

# Build rule for target.
example_remote: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_remote
.PHONY : example_remote

# fast build rule for target.
example_remote/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_remote.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_remote.dir/build
.PHONY : example_remote/fast

#=============================================================================
# Target rules for targets named example2

# Build rule for target.
example2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example2
.PHONY : example2

# fast build rule for target.
example2/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example2.dir/build.make ctest/tools/monetdbe/CMakeFiles/example2.dir/build
.PHONY : example2/fast

#=============================================================================
# Target rules for targets named example_temporal

# Build rule for target.
example_temporal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_temporal
.PHONY : example_temporal

# fast build rule for target.
example_temporal/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_temporal.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_temporal.dir/build
.PHONY : example_temporal/fast

#=============================================================================
# Target rules for targets named example_decimals

# Build rule for target.
example_decimals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_decimals
.PHONY : example_decimals

# fast build rule for target.
example_decimals/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_decimals.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_decimals.dir/build
.PHONY : example_decimals/fast

#=============================================================================
# Target rules for targets named example_backup

# Build rule for target.
example_backup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_backup
.PHONY : example_backup

# fast build rule for target.
example_backup/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_backup.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_backup.dir/build
.PHONY : example_backup/fast

#=============================================================================
# Target rules for targets named example_blob

# Build rule for target.
example_blob: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_blob
.PHONY : example_blob

# fast build rule for target.
example_blob/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_blob.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_blob.dir/build
.PHONY : example_blob/fast

#=============================================================================
# Target rules for targets named example_connections

# Build rule for target.
example_connections: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_connections
.PHONY : example_connections

# fast build rule for target.
example_connections/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_connections.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_connections.dir/build
.PHONY : example_connections/fast

#=============================================================================
# Target rules for targets named example_append

# Build rule for target.
example_append: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_append
.PHONY : example_append

# fast build rule for target.
example_append/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_append.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_append.dir/build
.PHONY : example_append/fast

#=============================================================================
# Target rules for targets named example_append_raw

# Build rule for target.
example_append_raw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_append_raw
.PHONY : example_append_raw

# fast build rule for target.
example_append_raw/fast:
	$(MAKE) -f ctest/tools/monetdbe/CMakeFiles/example_append_raw.dir/build.make ctest/tools/monetdbe/CMakeFiles/example_append_raw.dir/build
.PHONY : example_append_raw/fast

#=============================================================================
# Target rules for targets named documentation

# Build rule for target.
documentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 documentation
.PHONY : documentation

# fast build rule for target.
documentation/fast:
	$(MAKE) -f documentation/CMakeFiles/documentation.dir/build.make documentation/CMakeFiles/documentation.dir/build
.PHONY : documentation/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... package_source"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousUpdate"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousCoverage"
	@echo "... Experimental"
	@echo "... edit_cache"
	@echo "... NightlyMemCheck"
	@echo "... create-source-deb-packages"
	@echo "... create-deb-packages"
	@echo "... create-rpm-packages"
	@echo "... ContinuousBuild"
	@echo "... create-source-rpm-packages"
	@echo "... ContinuousStart"
	@echo "... ExperimentalUpdate"
	@echo "... create-rpm-distro"
	@echo "... mtest"
	@echo "... package"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... NightlyUpdate"
	@echo "... create-rpm-repo"
	@echo "... Continuous"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... NightlyConfigure"
	@echo "... NightlyTest"
	@echo "... NightlyCoverage"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... install"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... create-wix-packages"
	@echo "... ExperimentalStart"
	@echo "... moptions"
	@echo "... stream"
	@echo "... mutils"
	@echo "... mcrypt"
	@echo "... msabaoth"
	@echo "... mprompt"
	@echo "... msqldump"
	@echo "... mclient"
	@echo "... stethoscope"
	@echo "... mcutil"
	@echo "... mapi"
	@echo "... MonetODBCs"
	@echo "... MonetODBC"
	@echo "... testStmtAttr"
	@echo "... arraytest"
	@echo "... testgetinfo"
	@echo "... odbcsample1"
	@echo "... sample1"
	@echo "... smack00"
	@echo "... smack01"
	@echo "... streamcat"
	@echo "... sample4"
	@echo "... sample0"
	@echo "... bat"
	@echo "... mal"
	@echo "... atoms"
	@echo "... malmodules"
	@echo "... microbenchmark"
	@echo "... kernel"
	@echo "... optimizer"
	@echo "... run_isolate"
	@echo "... run_memo"
	@echo "... run_adder"
	@echo "... monetdb5"
	@echo "... opt_sql_append"
	@echo "... sql"
	@echo "... generator"
	@echo "... udf"
	@echo "... capi"
	@echo "... pyapi3"
	@echo "... sqlcommon"
	@echo "... sqlserver"
	@echo "... sqlstorage"
	@echo "... batstore"
	@echo "... monetdb"
	@echo "... monetdbd"
	@echo "... meroutil"
	@echo "... shutdowntest"
	@echo "... mserver5"
	@echo "... monetdbe"
	@echo "... Mdiff"
	@echo "... test_malInclude"
	@echo "... test_malEmbeddedBoot"
	@echo "... example1"
	@echo "... example_remote"
	@echo "... example2"
	@echo "... example_temporal"
	@echo "... example_decimals"
	@echo "... example_backup"
	@echo "... example_blob"
	@echo "... example_connections"
	@echo "... example_append"
	@echo "... example_append_raw"
	@echo "... documentation"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

